version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=me
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=api
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: